#ifndef VERSION_H
#define VERSION_H

#define ORION_VERSION_MAJOR 0
#define ORION_VERSION_MINOR 3
#define ORION_VERSION_PATCH 6
#define ORION_VERSION_BUILD 2

#define ORION_VERSION_STRING "0.3.6.2"

#endif
